### ISSUE TITLE
[Bug] Rendered/Total (and $current) on jobs is incorrect

### ISSUE THREAD

**Issue by stephen304** [oenvoyage/brender#27]
The jobs page always shows 100% under the rendered/total column (50/50, 110/110). I am unsure whether this problem only exists when restarting a previously completed job or whether it is present in all jobs. Possibly related to the fact that rendered frames (in MySQL) are not removed from the table when the job is restarted.

**Comment by stephen304** [comment]
Jobs.php Line 136
`$total_rendered=$total_frames;`

Perhaps this was a placeholder? It would make more sense to have:
`$total_rendered=$current;`
but $current seems to be off as well. (Showing Current: 55, Rendered: 50/50)

**Comment by oenvoyage** [comment]
Hello
count_rendered frames is actually an information of how many files are already rendered in the output folder... 
it was disabled as it became very slow on big projects :
i commented out line 135 on jobs.php
#$total_rendered=count_rendered_frames($id);
if you enable it it will browse your output files and see how many files he finds, it does not mean the files are ou to date (if you restarted a job)
it is only accurate the first time you render, as if you re-render, it will overwrite the files which already exist.
Maybe it is not straighforward to understand i admit... the column could be deleted, as the most precise way to check your job progress is the overall progress bar, and the "current" value

**Comment by stephen304** [comment]
My friend suggests deleting the rendered frames when a job is restarted. I haven't looked at the function but I can't imagine why it would be slow if all it does is count the number of files in the folder.

**Comment by oenvoyage** [comment]
I am against deleting frames when job is restarted. We use this feature in production a lot... 
You can for instance render a first pass with low res models, low samples and subdivision, still get a fairly good looking render, you can start compositing and finalise the edit using those renders. You then restart the final render with better quality and hi-res models. It get replaced.
It is also useful for re-rendering only some parts of a long animation... 

Sometimes count_rendered_frames() can gets slow because the function does not count how many frames, but checks if each individual frames exists... which means 2400 file_exists() check for a 2400 frame anim. Slow on network drives
I re-enabled it for now ... on todo would be to improve that function.

**Comment by stephen304** [comment]
How about a checkbox on update job that would delete the rendered frames (or maybe the whole render folder) before job restart?
The rendered/total should take into account that some of the frames are being re-rendered. It needs to at least take count_rendered_frames() and add or subtract based on the current job info to get the amount that are completed.

**Comment by oenvoyage** [comment]
Yes this sounds Ok to me.
On Jan 4, 2012 1:27 AM, "Stephen Smith" <
reply@reply.github.com>
wrote:
