### ISSUE TITLE
batch / python script for server / client configuration

### ISSUE THREAD

**Issue by DanielRuf** [oenvoyage/brender#30]
I am currently thinking about a batch / python script that uses a config file and sets up the srver / client automatically.

Also why not (just a stupid idea) create a fully portable server (xampp / uniform) or include it so we dont have to set it up. And the script makes config, install (cmd?) and startup of server and client

And that could be used as service running when the server starts.
So we save much manual tasks. Would be very great.

(Another question if it is possible to realize it with sqlite3 and python / java the whole brender program)

**Comment by stephen304** [comment]
You might find this interesting, but I'm currently working on an update script that can be executed instead of the main brender client. I am making this php script so that I can have remote nodes (that are REALLY remote, like my friend who lives a couple hours away) which will automatically check for updates then do folder comparison, and md5 comparison if necessary then delete/update/download new files automatically then launch brender via brender_client. If I add a setting at the top of the script for update server/address, the script could be given to people, they enter their update server's address and upload the corresponding update script on their update server along with their copy of brender then simply run the update script on the client machines.

**Comment by DanielRuf** [comment]
Well you are talking about a php script but I mean a batch / shell / python script that sets up client / server and can be run as service on startup so it starts the bundled server (xampp / uniform) automatically (they are fully portable)  inst it something totally different?

**Comment by stephen304** [comment]
I see what you mean by fully portable. I intend to make a fully portable client, minus the php since I am not using any remote windows render nodes and php comes installed on macs already. My script is going to have a few variables at the top for server info. This 1 file can be placed on any mac and started, everything else will be automated. It will connect to the server, download brender, set variables for brender, then launch brender. It's more intended to be an update script, though I would be interested in your solution for a portable client as well.

**Comment by DanielRuf** [comment]
Well mac, but I want to focus on crossplatform. It is great if you make it for mac but thats not enough =)
So its not very usable for all users. Would be much better if you could go the way that I meant for all platforms. 

Currently I have not so much time to realize my idea directly but it would be great to get some support and help for this.

**Comment by oenvoyage** [comment]
Hello,
the idea about setting up a LAMP, MAMP, WAMP server, fully setup with brender is a good idea... I am not sure if the license does allow redistributing.
Needs to be investigated. 
Was it hard for you guys to set brender up ?

**Comment by DanielRuf** [comment]
It does allow redistributing if I think
The Uniform Server is BSD (http://en.wikipedia.org/wiki/The_Uniform_Server) and XAMPP (which is maybe much better becase it is crossplatform) is mostly GPL (http://de.wikipedia.org/wiki/XAMPP#Lizenz)

Yes it was sometimes hard to set it up on some clients and we had to repeat all the steps again and again for each server and client.  

A batch script that installs / setups brender including all config things and the server (if installed on server) helps a lot to setup many clients (we will use in the future some racks with many cuda clients and servers) automatically and run them permanently (as a service at startup)

Think about the manual installing of linux or another os on many clients and servers against the automatic installation over network or from a script / cd ...  saves much time and problems

Also good is an installer / config tool done with izpack doing all this. So no manual config and install.
